// <copyright file="AccessibilityV2.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// AccessibilityV2.
    /// </summary>
    public class AccessibilityV2
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccessibilityV2"/> class.
        /// </summary>
        public AccessibilityV2()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccessibilityV2"/> class.
        /// </summary>
        /// <param name="status">status.</param>
        public AccessibilityV2(
            Models.AccessibilityStatusEnum? status = null)
        {
            this.Status = status;
        }

        /// <summary>
        /// Accessibility Status
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public Models.AccessibilityStatusEnum? Status { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AccessibilityV2 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AccessibilityV2 other &&
                (this.Status == null && other.Status == null ||
                 this.Status?.Equals(other.Status) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Status = {(this.Status == null ? "null" : this.Status.ToString())}");
        }
    }
}