// <copyright file="AccessibilityStatusEnum.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// AccessibilityStatusEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum AccessibilityStatusEnum
    {
        /// <summary>
        /// FreePublic.
        /// </summary>
        [EnumMember(Value = "FreePublic")]
        FreePublic,

        /// <summary>
        /// PayingPublic.
        /// </summary>
        [EnumMember(Value = "PayingPublic")]
        PayingPublic,

        /// <summary>
        /// Restricted.
        /// </summary>
        [EnumMember(Value = "Restricted")]
        Restricted,

        /// <summary>
        /// Unspecified.
        /// </summary>
        [EnumMember(Value = "Unspecified")]
        Unspecified
    }
}