// <copyright file="ConnectorV2.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// ConnectorV2.
    /// </summary>
    public class ConnectorV2
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectorV2"/> class.
        /// </summary>
        public ConnectorV2()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectorV2"/> class.
        /// </summary>
        /// <param name="uid">uid.</param>
        /// <param name="externalId">externalId.</param>
        /// <param name="connectorType">connectorType.</param>
        /// <param name="electricalProperties">electricalProperties.</param>
        public ConnectorV2(
            string uid = null,
            string externalId = null,
            Models.ConnectorVOConnectorTypeEnum? connectorType = null,
            Models.ElectricalPropertiesV2 electricalProperties = null)
        {
            this.Uid = uid;
            this.ExternalId = externalId;
            this.ConnectorType = connectorType;
            this.ElectricalProperties = electricalProperties;
        }

        /// <summary>
        /// Internal identifier used to refer to this Connector
        /// </summary>
        [JsonProperty("uid", NullValueHandling = NullValueHandling.Ignore)]
        public string Uid { get; set; }

        /// <summary>
        /// Identifier of the Evse as given by the Operator, unique for the containing EVSE'
        /// </summary>
        [JsonProperty("externalId", NullValueHandling = NullValueHandling.Ignore)]
        public string ExternalId { get; set; }

        /// <summary>
        /// Type of the connector in the EVSE unit.
        /// </summary>
        [JsonProperty("connectorType", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ConnectorVOConnectorTypeEnum? ConnectorType { get; set; }

        /// <summary>
        /// Electrical Properties of the Connector
        /// </summary>
        [JsonProperty("electricalProperties", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ElectricalPropertiesV2 ElectricalProperties { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ConnectorV2 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ConnectorV2 other &&
                (this.Uid == null && other.Uid == null ||
                 this.Uid?.Equals(other.Uid) == true) &&
                (this.ExternalId == null && other.ExternalId == null ||
                 this.ExternalId?.Equals(other.ExternalId) == true) &&
                (this.ConnectorType == null && other.ConnectorType == null ||
                 this.ConnectorType?.Equals(other.ConnectorType) == true) &&
                (this.ElectricalProperties == null && other.ElectricalProperties == null ||
                 this.ElectricalProperties?.Equals(other.ElectricalProperties) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Uid = {this.Uid ?? "null"}");
            toStringOutput.Add($"ExternalId = {this.ExternalId ?? "null"}");
            toStringOutput.Add($"ConnectorType = {(this.ConnectorType == null ? "null" : this.ConnectorType.ToString())}");
            toStringOutput.Add($"ElectricalProperties = {(this.ElectricalProperties == null ? "null" : this.ElectricalProperties.ToString())}");
        }
    }
}