// <copyright file="ConnectorVOUpdatedByEnum.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// ConnectorVOUpdatedByEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ConnectorVOUpdatedByEnum
    {
        /// <summary>
        /// Feed.
        /// </summary>
        [EnumMember(Value = "Feed")]
        Feed,

        /// <summary>
        /// Admin.
        /// </summary>
        [EnumMember(Value = "Admin")]
        Admin,

        /// <summary>
        /// TariffService.
        /// </summary>
        [EnumMember(Value = "TariffService")]
        TariffService,

        /// <summary>
        /// Defaults.
        /// </summary>
        [EnumMember(Value = "Defaults")]
        Defaults
    }
}