// <copyright file="DayOfWeekEnum.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// DayOfWeekEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum DayOfWeekEnum
    {
        /// <summary>
        /// MONDAY.
        /// </summary>
        [EnumMember(Value = "MONDAY")]
        MONDAY,

        /// <summary>
        /// TUESDAY.
        /// </summary>
        [EnumMember(Value = "TUESDAY")]
        TUESDAY,

        /// <summary>
        /// WEDNESDAY.
        /// </summary>
        [EnumMember(Value = "WEDNESDAY")]
        WEDNESDAY,

        /// <summary>
        /// THURSDAY.
        /// </summary>
        [EnumMember(Value = "THURSDAY")]
        THURSDAY,

        /// <summary>
        /// FRIDAY.
        /// </summary>
        [EnumMember(Value = "FRIDAY")]
        FRIDAY,

        /// <summary>
        /// SATURDAY.
        /// </summary>
        [EnumMember(Value = "SATURDAY")]
        SATURDAY,

        /// <summary>
        /// SUNDAY.
        /// </summary>
        [EnumMember(Value = "SUNDAY")]
        SUNDAY
    }
}