// <copyright file="ElectricalPropertiesPowerTypeEnum.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// ElectricalPropertiesPowerTypeEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ElectricalPropertiesPowerTypeEnum
    {
        /// <summary>
        /// AC1Phase.
        /// </summary>
        [EnumMember(Value = "AC1Phase")]
        AC1Phase,

        /// <summary>
        /// AC3Phase.
        /// </summary>
        [EnumMember(Value = "AC3Phase")]
        AC3Phase,

        /// <summary>
        /// DC.
        /// </summary>
        [EnumMember(Value = "DC")]
        DC
    }
}