// <copyright file="EvseV2.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// EvseV2.
    /// </summary>
    public class EvseV2
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EvseV2"/> class.
        /// </summary>
        public EvseV2()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EvseV2"/> class.
        /// </summary>
        /// <param name="uid">uid.</param>
        /// <param name="externalId">externalId.</param>
        /// <param name="evseId">evseId.</param>
        /// <param name="status">status.</param>
        /// <param name="updated">updated.</param>
        /// <param name="physicalReference">physicalReference.</param>
        /// <param name="connectors">connectors.</param>
        /// <param name="authorizationMethods">authorizationMethods.</param>
        public EvseV2(
            string uid = null,
            string externalId = null,
            string evseId = null,
            Models.EvseVOStatusEnum? status = null,
            string updated = null,
            string physicalReference = null,
            List<Models.ConnectorV2> connectors = null,
            List<Models.SingleLocationMarkerAuthorizationMethodsItemsEnum> authorizationMethods = null)
        {
            this.Uid = uid;
            this.ExternalId = externalId;
            this.EvseId = evseId;
            this.Status = status;
            this.Updated = updated;
            this.PhysicalReference = physicalReference;
            this.Connectors = connectors;
            this.AuthorizationMethods = authorizationMethods;
        }

        /// <summary>
        /// Internal identifier used to refer to single individual  EVSE unit.
        /// </summary>
        [JsonProperty("uid", NullValueHandling = NullValueHandling.Ignore)]
        public string Uid { get; set; }

        /// <summary>
        /// Identifier of the Evse as given by the Operator, unique for that Operator
        /// </summary>
        [JsonProperty("externalId", NullValueHandling = NullValueHandling.Ignore)]
        public string ExternalId { get; set; }

        /// <summary>
        /// Standard EVSEId identifier (ISO-IEC-15118)
        /// </summary>
        [JsonProperty("evseId", NullValueHandling = NullValueHandling.Ignore)]
        public string EvseId { get; set; }

        /// <summary>
        /// The current status of the EVSE units availability
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public Models.EvseVOStatusEnum? Status { get; set; }

        /// <summary>
        /// ISO8601-compliant UTC datetime of the last update of the EVSE
        /// </summary>
        [JsonProperty("updated", NullValueHandling = NullValueHandling.Ignore)]
        public string Updated { get; set; }

        /// <summary>
        /// An optional number/string printed on the outside of the EVSE for visual identification
        /// </summary>
        [JsonProperty("physicalReference", NullValueHandling = NullValueHandling.Ignore)]
        public string PhysicalReference { get; set; }

        /// <summary>
        /// List of all connectors available on this EVSE unit.
        /// </summary>
        [JsonProperty("connectors", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ConnectorV2> Connectors { get; set; }

        /// <summary>
        /// Methods that can be used to Authorize sessions on this EVSE
        /// </summary>
        [JsonProperty("authorizationMethods", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.SingleLocationMarkerAuthorizationMethodsItemsEnum> AuthorizationMethods { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"EvseV2 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is EvseV2 other &&
                (this.Uid == null && other.Uid == null ||
                 this.Uid?.Equals(other.Uid) == true) &&
                (this.ExternalId == null && other.ExternalId == null ||
                 this.ExternalId?.Equals(other.ExternalId) == true) &&
                (this.EvseId == null && other.EvseId == null ||
                 this.EvseId?.Equals(other.EvseId) == true) &&
                (this.Status == null && other.Status == null ||
                 this.Status?.Equals(other.Status) == true) &&
                (this.Updated == null && other.Updated == null ||
                 this.Updated?.Equals(other.Updated) == true) &&
                (this.PhysicalReference == null && other.PhysicalReference == null ||
                 this.PhysicalReference?.Equals(other.PhysicalReference) == true) &&
                (this.Connectors == null && other.Connectors == null ||
                 this.Connectors?.Equals(other.Connectors) == true) &&
                (this.AuthorizationMethods == null && other.AuthorizationMethods == null ||
                 this.AuthorizationMethods?.Equals(other.AuthorizationMethods) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Uid = {this.Uid ?? "null"}");
            toStringOutput.Add($"ExternalId = {this.ExternalId ?? "null"}");
            toStringOutput.Add($"EvseId = {this.EvseId ?? "null"}");
            toStringOutput.Add($"Status = {(this.Status == null ? "null" : this.Status.ToString())}");
            toStringOutput.Add($"Updated = {this.Updated ?? "null"}");
            toStringOutput.Add($"PhysicalReference = {this.PhysicalReference ?? "null"}");
            toStringOutput.Add($"Connectors = {(this.Connectors == null ? "null" : $"[{string.Join(", ", this.Connectors)} ]")}");
            toStringOutput.Add($"AuthorizationMethods = {(this.AuthorizationMethods == null ? "null" : $"[{string.Join(", ", this.AuthorizationMethods)} ]")}");
        }
    }
}