// <copyright file="GetEVLocationsEvseStatusEnum.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// GetEVLocationsEvseStatusEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum GetEVLocationsEvseStatusEnum
    {
        /// <summary>
        /// Available.
        /// </summary>
        [EnumMember(Value = "Available")]
        Available,

        /// <summary>
        /// Occupied.
        /// </summary>
        [EnumMember(Value = "Occupied")]
        Occupied,

        /// <summary>
        /// Unavailable.
        /// </summary>
        [EnumMember(Value = "Unavailable")]
        Unavailable,

        /// <summary>
        /// Unknown.
        /// </summary>
        [EnumMember(Value = "Unknown")]
        Unknown
    }
}