// <copyright file="LocationResponeObjectV2.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// LocationResponeObjectV2.
    /// </summary>
    public class LocationResponeObjectV2
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LocationResponeObjectV2"/> class.
        /// </summary>
        public LocationResponeObjectV2()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LocationResponeObjectV2"/> class.
        /// </summary>
        /// <param name="uid">uid.</param>
        /// <param name="externalId">externalId.</param>
        /// <param name="coordinates">coordinates.</param>
        /// <param name="operatorName">operatorName.</param>
        /// <param name="address">address.</param>
        /// <param name="accessibility">accessibility.</param>
        /// <param name="evses">evses.</param>
        /// <param name="openingHours">openingHours.</param>
        /// <param name="updated">updated.</param>
        /// <param name="locationType">locationType.</param>
        /// <param name="operatorId">operatorId.</param>
        /// <param name="openTwentyFourSeven">openTwentyFourSeven.</param>
        public LocationResponeObjectV2(
            string uid = null,
            string externalId = null,
            Models.Coordinates coordinates = null,
            string operatorName = null,
            Models.Address address = null,
            Models.AccessibilityV2 accessibility = null,
            List<Models.EvseV2> evses = null,
            List<Models.OpeningHoursObject> openingHours = null,
            string updated = null,
            string locationType = null,
            string operatorId = null,
            bool? openTwentyFourSeven = null)
        {
            this.Uid = uid;
            this.ExternalId = externalId;
            this.Coordinates = coordinates;
            this.OperatorName = operatorName;
            this.Address = address;
            this.Accessibility = accessibility;
            this.Evses = evses;
            this.OpeningHours = openingHours;
            this.Updated = updated;
            this.LocationType = locationType;
            this.OperatorId = operatorId;
            this.OpenTwentyFourSeven = openTwentyFourSeven;
        }

        /// <summary>
        /// Unique Internal identifier used to refer to this Location by Shell Recharge
        /// </summary>
        [JsonProperty("uid", NullValueHandling = NullValueHandling.Ignore)]
        public string Uid { get; set; }

        /// <summary>
        /// Identifier as given by the Shell Recharge Operator, unique for that Operator
        /// </summary>
        [JsonProperty("externalId", NullValueHandling = NullValueHandling.Ignore)]
        public string ExternalId { get; set; }

        /// <summary>
        /// Coordinates of the Shell Recharge Site Location
        /// </summary>
        [JsonProperty("coordinates", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Coordinates Coordinates { get; set; }

        /// <summary>
        /// Operator of this Shell Recharge Location
        /// </summary>
        [JsonProperty("operatorName", NullValueHandling = NullValueHandling.Ignore)]
        public string OperatorName { get; set; }

        /// <summary>
        /// Address of the Shell Recharge Location
        /// </summary>
        [JsonProperty("address", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Address Address { get; set; }

        /// <summary>
        /// Accessibility of the Location
        /// </summary>
        [JsonProperty("accessibility", NullValueHandling = NullValueHandling.Ignore)]
        public Models.AccessibilityV2 Accessibility { get; set; }

        /// <summary>
        /// Gets or sets Evses.
        /// </summary>
        [JsonProperty("evses", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.EvseV2> Evses { get; set; }

        /// <summary>
        /// Optional Opening Hours of the Location. Please note that it is not available for all sites.
        /// </summary>
        [JsonProperty("openingHours", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.OpeningHoursObject> OpeningHours { get; set; }

        /// <summary>
        /// ISO8601-compliant UTC datetime of the last update of the location
        /// </summary>
        [JsonProperty("updated", NullValueHandling = NullValueHandling.Ignore)]
        public string Updated { get; set; }

        /// <summary>
        /// the type of the location. Could be "UNKNOWN".
        /// </summary>
        [JsonProperty("locationType", NullValueHandling = NullValueHandling.Ignore)]
        public string LocationType { get; set; }

        /// <summary>
        /// Unique Id of the operator
        /// </summary>
        [JsonProperty("operatorId", NullValueHandling = NullValueHandling.Ignore)]
        public string OperatorId { get; set; }

        /// <summary>
        /// Whether the location is open 24/7
        /// </summary>
        [JsonProperty("openTwentyFourSeven", NullValueHandling = NullValueHandling.Ignore)]
        public bool? OpenTwentyFourSeven { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"LocationResponeObjectV2 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is LocationResponeObjectV2 other &&
                (this.Uid == null && other.Uid == null ||
                 this.Uid?.Equals(other.Uid) == true) &&
                (this.ExternalId == null && other.ExternalId == null ||
                 this.ExternalId?.Equals(other.ExternalId) == true) &&
                (this.Coordinates == null && other.Coordinates == null ||
                 this.Coordinates?.Equals(other.Coordinates) == true) &&
                (this.OperatorName == null && other.OperatorName == null ||
                 this.OperatorName?.Equals(other.OperatorName) == true) &&
                (this.Address == null && other.Address == null ||
                 this.Address?.Equals(other.Address) == true) &&
                (this.Accessibility == null && other.Accessibility == null ||
                 this.Accessibility?.Equals(other.Accessibility) == true) &&
                (this.Evses == null && other.Evses == null ||
                 this.Evses?.Equals(other.Evses) == true) &&
                (this.OpeningHours == null && other.OpeningHours == null ||
                 this.OpeningHours?.Equals(other.OpeningHours) == true) &&
                (this.Updated == null && other.Updated == null ||
                 this.Updated?.Equals(other.Updated) == true) &&
                (this.LocationType == null && other.LocationType == null ||
                 this.LocationType?.Equals(other.LocationType) == true) &&
                (this.OperatorId == null && other.OperatorId == null ||
                 this.OperatorId?.Equals(other.OperatorId) == true) &&
                (this.OpenTwentyFourSeven == null && other.OpenTwentyFourSeven == null ||
                 this.OpenTwentyFourSeven?.Equals(other.OpenTwentyFourSeven) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Uid = {this.Uid ?? "null"}");
            toStringOutput.Add($"ExternalId = {this.ExternalId ?? "null"}");
            toStringOutput.Add($"Coordinates = {(this.Coordinates == null ? "null" : this.Coordinates.ToString())}");
            toStringOutput.Add($"OperatorName = {this.OperatorName ?? "null"}");
            toStringOutput.Add($"Address = {(this.Address == null ? "null" : this.Address.ToString())}");
            toStringOutput.Add($"Accessibility = {(this.Accessibility == null ? "null" : this.Accessibility.ToString())}");
            toStringOutput.Add($"Evses = {(this.Evses == null ? "null" : $"[{string.Join(", ", this.Evses)} ]")}");
            toStringOutput.Add($"OpeningHours = {(this.OpeningHours == null ? "null" : $"[{string.Join(", ", this.OpeningHours)} ]")}");
            toStringOutput.Add($"Updated = {this.Updated ?? "null"}");
            toStringOutput.Add($"LocationType = {this.LocationType ?? "null"}");
            toStringOutput.Add($"OperatorId = {this.OperatorId ?? "null"}");
            toStringOutput.Add($"OpenTwentyFourSeven = {(this.OpenTwentyFourSeven == null ? "null" : this.OpenTwentyFourSeven.ToString())}");
        }
    }
}