// <copyright file="MultiLocationMarkerV2.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// MultiLocationMarkerV2.
    /// </summary>
    public class MultiLocationMarkerV2
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MultiLocationMarkerV2"/> class.
        /// </summary>
        public MultiLocationMarkerV2()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MultiLocationMarkerV2"/> class.
        /// </summary>
        /// <param name="markerType">markerType.</param>
        /// <param name="coordinates">coordinates.</param>
        /// <param name="locationCount">locationCount.</param>
        /// <param name="evseCount">evseCount.</param>
        /// <param name="maxPower">maxPower.</param>
        /// <param name="operatorName">operatorName.</param>
        public MultiLocationMarkerV2(
            string markerType,
            Models.Coordinates coordinates = null,
            double? locationCount = null,
            double? evseCount = null,
            double? maxPower = null,
            string operatorName = null)
        {
            this.Coordinates = coordinates;
            this.LocationCount = locationCount;
            this.EvseCount = evseCount;
            this.MaxPower = maxPower;
            this.OperatorName = operatorName;
            this.MarkerType = markerType;
        }

        /// <summary>
        /// Coordinates of the Shell Recharge Site Location
        /// </summary>
        [JsonProperty("coordinates", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Coordinates Coordinates { get; set; }

        /// <summary>
        /// Number of Locations that this Marker represents in the given set of bounds
        /// </summary>
        [JsonProperty("locationCount", NullValueHandling = NullValueHandling.Ignore)]
        public double? LocationCount { get; set; }

        /// <summary>
        /// Total number of Evses in Locations that this Marker represents
        /// </summary>
        [JsonProperty("evseCount", NullValueHandling = NullValueHandling.Ignore)]
        public double? EvseCount { get; set; }

        /// <summary>
        /// Maximum power in kW across all locations grouped in this marker (disregarding availability)
        /// </summary>
        [JsonProperty("maxPower", NullValueHandling = NullValueHandling.Ignore)]
        public double? MaxPower { get; set; }

        /// <summary>
        /// Operator of this Shell Recharge Location
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("operatorName", NullValueHandling = NullValueHandling.Ignore)]
        public string OperatorName { get; set; }

        /// <summary>
        /// Type of the Marker, in this case it will always be MultiLocation
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("markerType")]
        [JsonRequired]
        public string MarkerType { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"MultiLocationMarkerV2 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is MultiLocationMarkerV2 other &&
                (this.Coordinates == null && other.Coordinates == null ||
                 this.Coordinates?.Equals(other.Coordinates) == true) &&
                (this.LocationCount == null && other.LocationCount == null ||
                 this.LocationCount?.Equals(other.LocationCount) == true) &&
                (this.EvseCount == null && other.EvseCount == null ||
                 this.EvseCount?.Equals(other.EvseCount) == true) &&
                (this.MaxPower == null && other.MaxPower == null ||
                 this.MaxPower?.Equals(other.MaxPower) == true) &&
                (this.OperatorName == null && other.OperatorName == null ||
                 this.OperatorName?.Equals(other.OperatorName) == true) &&
                (this.MarkerType == null && other.MarkerType == null ||
                 this.MarkerType?.Equals(other.MarkerType) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Coordinates = {(this.Coordinates == null ? "null" : this.Coordinates.ToString())}");
            toStringOutput.Add($"LocationCount = {(this.LocationCount == null ? "null" : this.LocationCount.ToString())}");
            toStringOutput.Add($"EvseCount = {(this.EvseCount == null ? "null" : this.EvseCount.ToString())}");
            toStringOutput.Add($"MaxPower = {(this.MaxPower == null ? "null" : this.MaxPower.ToString())}");
            toStringOutput.Add($"OperatorName = {this.OperatorName ?? "null"}");
            toStringOutput.Add($"MarkerType = {this.MarkerType ?? "null"}");
        }
    }
}