// <copyright file="PowerRange.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// PowerRange.
    /// </summary>
    public class PowerRange
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PowerRange"/> class.
        /// </summary>
        public PowerRange()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PowerRange"/> class.
        /// </summary>
        /// <param name="min">min.</param>
        /// <param name="max">max.</param>
        public PowerRange(
            int min,
            int max)
        {
            this.Min = min;
            this.Max = max;
        }

        /// <summary>
        /// Minimum supported power in kW
        /// </summary>
        [JsonProperty("min")]
        public int Min { get; set; }

        /// <summary>
        /// Maximum supported power in kW
        /// </summary>
        [JsonProperty("max")]
        public int Max { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PowerRange : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is PowerRange other &&
                (this.Min.Equals(other.Min)) &&
                (this.Max.Equals(other.Max));
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Min = {this.Min}");
            toStringOutput.Add($"Max = {this.Max}");
        }
    }
}