// <copyright file="PriceComponent.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// PriceComponent.
    /// </summary>
    public class PriceComponent
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PriceComponent"/> class.
        /// </summary>
        public PriceComponent()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PriceComponent"/> class.
        /// </summary>
        /// <param name="type">type.</param>
        /// <param name="stepSize">stepSize.</param>
        /// <param name="price">price.</param>
        /// <param name="vat">vat.</param>
        public PriceComponent(
            Models.TypeEnum type,
            int stepSize,
            double price,
            double vat)
        {
            this.Type = type;
            this.StepSize = stepSize;
            this.Price = price;
            this.Vat = vat;
        }

        /// <summary>
        /// Type of the price component
        /// </summary>
        [JsonProperty("type")]
        public Models.TypeEnum Type { get; set; }

        /// <summary>
        /// Step size in seconds for TIME-based components, in kWh for ENERGY-based components, or 1 for FLAT components
        /// </summary>
        [JsonProperty("stepSize")]
        public int StepSize { get; set; }

        /// <summary>
        /// Price per step in the specified currency for this price component
        /// </summary>
        [JsonProperty("price")]
        public double Price { get; set; }

        /// <summary>
        /// VAT percentage applicable to this price component
        /// </summary>
        [JsonProperty("vat")]
        public double Vat { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PriceComponent : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is PriceComponent other &&
                (this.Type.Equals(other.Type)) &&
                (this.StepSize.Equals(other.StepSize)) &&
                (this.Price.Equals(other.Price)) &&
                (this.Vat.Equals(other.Vat));
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Type = {this.Type}");
            toStringOutput.Add($"StepSize = {this.StepSize}");
            toStringOutput.Add($"Price = {this.Price}");
            toStringOutput.Add($"Vat = {this.Vat}");
        }
    }
}