// <copyright file="Restrictions.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using ShellEV.Standard.Utilities;
using System;
using System.Collections.Generic;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// Restrictions.
    /// </summary>
    public class Restrictions
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Restrictions"/> class.
        /// </summary>
        public Restrictions()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Restrictions"/> class.
        /// </summary>
        /// <param name="startTime">startTime.</param>
        /// <param name="endTime">endTime.</param>
        /// <param name="startDate">startDate.</param>
        /// <param name="endDate">endDate.</param>
        /// <param name="minKwh">minKwh.</param>
        /// <param name="maxKwh">maxKwh.</param>
        /// <param name="minCurrent">minCurrent.</param>
        /// <param name="maxCurrent">maxCurrent.</param>
        /// <param name="minPower">minPower.</param>
        /// <param name="maxPower">maxPower.</param>
        /// <param name="minDuration">minDuration.</param>
        /// <param name="maxDuration">maxDuration.</param>
        /// <param name="dayOfWeek">dayOfWeek.</param>
        public Restrictions(
            string startTime = null,
            string endTime = null,
            DateTime? startDate = null,
            DateTime? endDate = null,
            double? minKwh = null,
            double? maxKwh = null,
            double? minCurrent = null,
            double? maxCurrent = null,
            double? minPower = null,
            double? maxPower = null,
            int? minDuration = null,
            int? maxDuration = null,
            List<Models.DayOfWeekEnum> dayOfWeek = null)
        {
            this.StartTime = startTime;
            this.EndTime = endTime;
            this.StartDate = startDate;
            this.EndDate = endDate;
            this.MinKwh = minKwh;
            this.MaxKwh = maxKwh;
            this.MinCurrent = minCurrent;
            this.MaxCurrent = maxCurrent;
            this.MinPower = minPower;
            this.MaxPower = maxPower;
            this.MinDuration = minDuration;
            this.MaxDuration = maxDuration;
            this.DayOfWeek = dayOfWeek;
        }

        /// <summary>
        /// Valid from this time of the day (HH:mm)
        /// </summary>
        [JsonProperty("startTime", NullValueHandling = NullValueHandling.Ignore)]
        public string StartTime { get; set; }

        /// <summary>
        /// Valid until this time of the day (HH:mm)
        /// </summary>
        [JsonProperty("endTime", NullValueHandling = NullValueHandling.Ignore)]
        public string EndTime { get; set; }

        /// <summary>
        /// Gets or sets StartDate.
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("startDate", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? StartDate { get; set; }

        /// <summary>
        /// Gets or sets EndDate.
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("endDate", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? EndDate { get; set; }

        /// <summary>
        /// Gets or sets MinKwh.
        /// </summary>
        [JsonProperty("minKwh", NullValueHandling = NullValueHandling.Ignore)]
        public double? MinKwh { get; set; }

        /// <summary>
        /// Gets or sets MaxKwh.
        /// </summary>
        [JsonProperty("maxKwh", NullValueHandling = NullValueHandling.Ignore)]
        public double? MaxKwh { get; set; }

        /// <summary>
        /// Gets or sets MinCurrent.
        /// </summary>
        [JsonProperty("minCurrent", NullValueHandling = NullValueHandling.Ignore)]
        public double? MinCurrent { get; set; }

        /// <summary>
        /// Gets or sets MaxCurrent.
        /// </summary>
        [JsonProperty("maxCurrent", NullValueHandling = NullValueHandling.Ignore)]
        public double? MaxCurrent { get; set; }

        /// <summary>
        /// Gets or sets MinPower.
        /// </summary>
        [JsonProperty("minPower", NullValueHandling = NullValueHandling.Ignore)]
        public double? MinPower { get; set; }

        /// <summary>
        /// Gets or sets MaxPower.
        /// </summary>
        [JsonProperty("maxPower", NullValueHandling = NullValueHandling.Ignore)]
        public double? MaxPower { get; set; }

        /// <summary>
        /// Minimum session duration in seconds
        /// </summary>
        [JsonProperty("minDuration", NullValueHandling = NullValueHandling.Ignore)]
        public int? MinDuration { get; set; }

        /// <summary>
        /// Maximum session duration in seconds
        /// </summary>
        [JsonProperty("maxDuration", NullValueHandling = NullValueHandling.Ignore)]
        public int? MaxDuration { get; set; }

        /// <summary>
        /// Gets or sets DayOfWeek.
        /// </summary>
        [JsonProperty("dayOfWeek", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.DayOfWeekEnum> DayOfWeek { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Restrictions : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Restrictions other &&
                (this.StartTime == null && other.StartTime == null ||
                 this.StartTime?.Equals(other.StartTime) == true) &&
                (this.EndTime == null && other.EndTime == null ||
                 this.EndTime?.Equals(other.EndTime) == true) &&
                (this.StartDate == null && other.StartDate == null ||
                 this.StartDate?.Equals(other.StartDate) == true) &&
                (this.EndDate == null && other.EndDate == null ||
                 this.EndDate?.Equals(other.EndDate) == true) &&
                (this.MinKwh == null && other.MinKwh == null ||
                 this.MinKwh?.Equals(other.MinKwh) == true) &&
                (this.MaxKwh == null && other.MaxKwh == null ||
                 this.MaxKwh?.Equals(other.MaxKwh) == true) &&
                (this.MinCurrent == null && other.MinCurrent == null ||
                 this.MinCurrent?.Equals(other.MinCurrent) == true) &&
                (this.MaxCurrent == null && other.MaxCurrent == null ||
                 this.MaxCurrent?.Equals(other.MaxCurrent) == true) &&
                (this.MinPower == null && other.MinPower == null ||
                 this.MinPower?.Equals(other.MinPower) == true) &&
                (this.MaxPower == null && other.MaxPower == null ||
                 this.MaxPower?.Equals(other.MaxPower) == true) &&
                (this.MinDuration == null && other.MinDuration == null ||
                 this.MinDuration?.Equals(other.MinDuration) == true) &&
                (this.MaxDuration == null && other.MaxDuration == null ||
                 this.MaxDuration?.Equals(other.MaxDuration) == true) &&
                (this.DayOfWeek == null && other.DayOfWeek == null ||
                 this.DayOfWeek?.Equals(other.DayOfWeek) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"StartTime = {this.StartTime ?? "null"}");
            toStringOutput.Add($"EndTime = {this.EndTime ?? "null"}");
            toStringOutput.Add($"StartDate = {(this.StartDate == null ? "null" : this.StartDate.ToString())}");
            toStringOutput.Add($"EndDate = {(this.EndDate == null ? "null" : this.EndDate.ToString())}");
            toStringOutput.Add($"MinKwh = {(this.MinKwh == null ? "null" : this.MinKwh.ToString())}");
            toStringOutput.Add($"MaxKwh = {(this.MaxKwh == null ? "null" : this.MaxKwh.ToString())}");
            toStringOutput.Add($"MinCurrent = {(this.MinCurrent == null ? "null" : this.MinCurrent.ToString())}");
            toStringOutput.Add($"MaxCurrent = {(this.MaxCurrent == null ? "null" : this.MaxCurrent.ToString())}");
            toStringOutput.Add($"MinPower = {(this.MinPower == null ? "null" : this.MinPower.ToString())}");
            toStringOutput.Add($"MaxPower = {(this.MaxPower == null ? "null" : this.MaxPower.ToString())}");
            toStringOutput.Add($"MinDuration = {(this.MinDuration == null ? "null" : this.MinDuration.ToString())}");
            toStringOutput.Add($"MaxDuration = {(this.MaxDuration == null ? "null" : this.MaxDuration.ToString())}");
            toStringOutput.Add($"DayOfWeek = {(this.DayOfWeek == null ? "null" : $"[{string.Join(", ", this.DayOfWeek)} ]")}");
        }
    }
}