// <copyright file="SearchByIdConnector.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// SearchByIdConnector.
    /// </summary>
    public class SearchByIdConnector
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchByIdConnector"/> class.
        /// </summary>
        public SearchByIdConnector()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchByIdConnector"/> class.
        /// </summary>
        /// <param name="uid">uid.</param>
        /// <param name="externalId">externalId.</param>
        /// <param name="connectorType">connectorType.</param>
        /// <param name="electricalProperties">electricalProperties.</param>
        /// <param name="tariffs">tariffs.</param>
        public SearchByIdConnector(
            string uid = null,
            string externalId = null,
            Models.ConnectorVOConnectorTypeEnum? connectorType = null,
            Models.ElectricalPropertiesV2 electricalProperties = null,
            List<Models.TariffV2> tariffs = null)
        {
            this.Uid = uid;
            this.ExternalId = externalId;
            this.ConnectorType = connectorType;
            this.ElectricalProperties = electricalProperties;
            this.Tariffs = tariffs;
        }

        /// <summary>
        /// Internal identifier used to refer to this Connector
        /// </summary>
        [JsonProperty("uid", NullValueHandling = NullValueHandling.Ignore)]
        public string Uid { get; set; }

        /// <summary>
        /// Identifier of the Evse as given by the Operator, unique for the containing EVSE'
        /// </summary>
        [JsonProperty("externalId", NullValueHandling = NullValueHandling.Ignore)]
        public string ExternalId { get; set; }

        /// <summary>
        /// Type of the connector in the EVSE unit.
        /// </summary>
        [JsonProperty("connectorType", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ConnectorVOConnectorTypeEnum? ConnectorType { get; set; }

        /// <summary>
        /// Electrical Properties of the Connector
        /// </summary>
        [JsonProperty("electricalProperties", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ElectricalPropertiesV2 ElectricalProperties { get; set; }

        /// <summary>
        /// Tariffs applicable to this Connector
        /// </summary>
        [JsonProperty("tariffs", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.TariffV2> Tariffs { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SearchByIdConnector : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is SearchByIdConnector other &&
                (this.Uid == null && other.Uid == null ||
                 this.Uid?.Equals(other.Uid) == true) &&
                (this.ExternalId == null && other.ExternalId == null ||
                 this.ExternalId?.Equals(other.ExternalId) == true) &&
                (this.ConnectorType == null && other.ConnectorType == null ||
                 this.ConnectorType?.Equals(other.ConnectorType) == true) &&
                (this.ElectricalProperties == null && other.ElectricalProperties == null ||
                 this.ElectricalProperties?.Equals(other.ElectricalProperties) == true) &&
                (this.Tariffs == null && other.Tariffs == null ||
                 this.Tariffs?.Equals(other.Tariffs) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Uid = {this.Uid ?? "null"}");
            toStringOutput.Add($"ExternalId = {this.ExternalId ?? "null"}");
            toStringOutput.Add($"ConnectorType = {(this.ConnectorType == null ? "null" : this.ConnectorType.ToString())}");
            toStringOutput.Add($"ElectricalProperties = {(this.ElectricalProperties == null ? "null" : this.ElectricalProperties.ToString())}");
            toStringOutput.Add($"Tariffs = {(this.Tariffs == null ? "null" : $"[{string.Join(", ", this.Tariffs)} ]")}");
        }
    }
}