// <copyright file="SingleLocationMarkerResponseV2.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using ShellEV.Standard.Models.Containers;
using System;
using System.Collections.Generic;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// SingleLocationMarkerResponseV2.
    /// </summary>
    public class SingleLocationMarkerResponseV2
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SingleLocationMarkerResponseV2"/> class.
        /// </summary>
        public SingleLocationMarkerResponseV2()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SingleLocationMarkerResponseV2"/> class.
        /// </summary>
        /// <param name="requestId">requestId.</param>
        /// <param name="status">status.</param>
        /// <param name="data">data.</param>
        public SingleLocationMarkerResponseV2(
            Guid? requestId = null,
            string status = null,
            List<LocationMarkerV2> data = null)
        {
            this.RequestId = requestId;
            this.Status = status;
            this.Data = data;
        }

        /// <summary>
        /// requestId is unique identifier value that is attached to requests and messages that allow reference to a particular transaction or event chain.
        /// </summary>
        [JsonProperty("requestId", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? RequestId { get; set; }

        /// <summary>
        /// status of the API call
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets Data.
        /// </summary>
        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public List<LocationMarkerV2> Data { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SingleLocationMarkerResponseV2 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is SingleLocationMarkerResponseV2 other &&
                (this.RequestId == null && other.RequestId == null ||
                 this.RequestId?.Equals(other.RequestId) == true) &&
                (this.Status == null && other.Status == null ||
                 this.Status?.Equals(other.Status) == true) &&
                (this.Data == null && other.Data == null ||
                 this.Data?.Equals(other.Data) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"RequestId = {(this.RequestId == null ? "null" : this.RequestId.ToString())}");
            toStringOutput.Add($"Status = {this.Status ?? "null"}");
            toStringOutput.Add($"Data = {(this.Data == null ? "null" : this.Data.ToString())}");
        }
    }
}