// <copyright file="SingleLocationMarkerV2.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// SingleLocationMarkerV2.
    /// </summary>
    public class SingleLocationMarkerV2
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SingleLocationMarkerV2"/> class.
        /// </summary>
        public SingleLocationMarkerV2()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SingleLocationMarkerV2"/> class.
        /// </summary>
        /// <param name="markerType">markerType.</param>
        /// <param name="status">status.</param>
        /// <param name="coordinates">coordinates.</param>
        /// <param name="evseCount">evseCount.</param>
        /// <param name="maxPower">maxPower.</param>
        /// <param name="locationCount">locationCount.</param>
        /// <param name="locationUid">locationUid.</param>
        /// <param name="authorizationMethods">authorizationMethods.</param>
        /// <param name="operatorName">operatorName.</param>
        public SingleLocationMarkerV2(
            string markerType,
            Models.SingleLocationMarkerStatusEnum? status = null,
            Models.Coordinates coordinates = null,
            double? evseCount = null,
            double? maxPower = null,
            double? locationCount = null,
            string locationUid = null,
            List<Models.SingleLocationMarkerAuthorizationMethodsItemsEnum> authorizationMethods = null,
            string operatorName = null)
        {
            this.Status = status;
            this.Coordinates = coordinates;
            this.EvseCount = evseCount;
            this.MaxPower = maxPower;
            this.LocationCount = locationCount;
            this.LocationUid = locationUid;
            this.AuthorizationMethods = authorizationMethods;
            this.OperatorName = operatorName;
            this.MarkerType = markerType;
        }

        /// <summary>
        /// Minimum of all status values in the Marker, e.g. if at least one Evse in the Marker is available, the value will be available
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public Models.SingleLocationMarkerStatusEnum? Status { get; set; }

        /// <summary>
        /// Coordinates of the Shell Recharge Site Location
        /// </summary>
        [JsonProperty("coordinates", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Coordinates Coordinates { get; set; }

        /// <summary>
        /// Total number of Evse units in Locations that this Marker represents
        /// </summary>
        [JsonProperty("evseCount", NullValueHandling = NullValueHandling.Ignore)]
        public double? EvseCount { get; set; }

        /// <summary>
        /// Maximum power in kW across all locations grouped in this marker (disregarding availability)
        /// </summary>
        [JsonProperty("maxPower", NullValueHandling = NullValueHandling.Ignore)]
        public double? MaxPower { get; set; }

        /// <summary>
        /// Number of Locations that this Marker represents in the given set of bounds
        /// </summary>
        [JsonProperty("locationCount", NullValueHandling = NullValueHandling.Ignore)]
        public double? LocationCount { get; set; }

        /// <summary>
        /// Unique ID of the Location this Marker represents
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("locationUid", NullValueHandling = NullValueHandling.Ignore)]
        public string LocationUid { get; set; }

        /// <summary>
        /// Methods that can be used to Authorize sessions on this EVSE
        /// </summary>
        [JsonProperty("authorizationMethods", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.SingleLocationMarkerAuthorizationMethodsItemsEnum> AuthorizationMethods { get; set; }

        /// <summary>
        /// Operator of this Shell Recharge Location
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("operatorName", NullValueHandling = NullValueHandling.Ignore)]
        public string OperatorName { get; set; }

        /// <summary>
        /// Type of the Marker, in this case it will always be SingleLocation
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("markerType")]
        [JsonRequired]
        public string MarkerType { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SingleLocationMarkerV2 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is SingleLocationMarkerV2 other &&
                (this.Status == null && other.Status == null ||
                 this.Status?.Equals(other.Status) == true) &&
                (this.Coordinates == null && other.Coordinates == null ||
                 this.Coordinates?.Equals(other.Coordinates) == true) &&
                (this.EvseCount == null && other.EvseCount == null ||
                 this.EvseCount?.Equals(other.EvseCount) == true) &&
                (this.MaxPower == null && other.MaxPower == null ||
                 this.MaxPower?.Equals(other.MaxPower) == true) &&
                (this.LocationCount == null && other.LocationCount == null ||
                 this.LocationCount?.Equals(other.LocationCount) == true) &&
                (this.LocationUid == null && other.LocationUid == null ||
                 this.LocationUid?.Equals(other.LocationUid) == true) &&
                (this.AuthorizationMethods == null && other.AuthorizationMethods == null ||
                 this.AuthorizationMethods?.Equals(other.AuthorizationMethods) == true) &&
                (this.OperatorName == null && other.OperatorName == null ||
                 this.OperatorName?.Equals(other.OperatorName) == true) &&
                (this.MarkerType == null && other.MarkerType == null ||
                 this.MarkerType?.Equals(other.MarkerType) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Status = {(this.Status == null ? "null" : this.Status.ToString())}");
            toStringOutput.Add($"Coordinates = {(this.Coordinates == null ? "null" : this.Coordinates.ToString())}");
            toStringOutput.Add($"EvseCount = {(this.EvseCount == null ? "null" : this.EvseCount.ToString())}");
            toStringOutput.Add($"MaxPower = {(this.MaxPower == null ? "null" : this.MaxPower.ToString())}");
            toStringOutput.Add($"LocationCount = {(this.LocationCount == null ? "null" : this.LocationCount.ToString())}");
            toStringOutput.Add($"LocationUid = {this.LocationUid ?? "null"}");
            toStringOutput.Add($"AuthorizationMethods = {(this.AuthorizationMethods == null ? "null" : $"[{string.Join(", ", this.AuthorizationMethods)} ]")}");
            toStringOutput.Add($"OperatorName = {this.OperatorName ?? "null"}");
            toStringOutput.Add($"MarkerType = {this.MarkerType ?? "null"}");
        }
    }
}