// <copyright file="TariffTypeEnum.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// TariffTypeEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum TariffTypeEnum
    {
        /// <summary>
        /// DRIVER.
        /// </summary>
        [EnumMember(Value = "DRIVER")]
        DRIVER,

        /// <summary>
        /// ROAMING.
        /// </summary>
        [EnumMember(Value = "ROAMING")]
        ROAMING,

        /// <summary>
        /// REIMBURSEMENT.
        /// </summary>
        [EnumMember(Value = "REIMBURSEMENT")]
        REIMBURSEMENT,

        /// <summary>
        /// VMSP.
        /// </summary>
        [EnumMember(Value = "VMSP")]
        VMSP
    }
}