// <copyright file="TariffV2.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// TariffV2.
    /// </summary>
    public class TariffV2
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TariffV2"/> class.
        /// </summary>
        public TariffV2()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TariffV2"/> class.
        /// </summary>
        /// <param name="tariffId">tariffId.</param>
        /// <param name="tariffType">tariffType.</param>
        /// <param name="powerRange">powerRange.</param>
        /// <param name="internalId">internalId.</param>
        /// <param name="operatorId">operatorId.</param>
        /// <param name="providerId">providerId.</param>
        /// <param name="currency">currency.</param>
        /// <param name="minPrice">minPrice.</param>
        /// <param name="maxPrice">maxPrice.</param>
        /// <param name="elements">elements.</param>
        /// <param name="startDateTime">startDateTime.</param>
        /// <param name="endDateTime">endDateTime.</param>
        /// <param name="lastUpdated">lastUpdated.</param>
        /// <param name="createdBy">createdBy.</param>
        /// <param name="tariffAltText">tariffAltText.</param>
        public TariffV2(
            string tariffId,
            Models.TariffTypeEnum tariffType,
            Models.PowerRange powerRange,
            string internalId,
            string operatorId,
            string providerId,
            string currency,
            double minPrice,
            double maxPrice,
            List<Models.TariffElement> elements,
            DateTime startDateTime,
            DateTime endDateTime,
            DateTime lastUpdated,
            string createdBy,
            List<Models.TariffAltText> tariffAltText = null)
        {
            this.TariffId = tariffId;
            this.TariffType = tariffType;
            this.PowerRange = powerRange;
            this.InternalId = internalId;
            this.OperatorId = operatorId;
            this.ProviderId = providerId;
            this.Currency = currency;
            this.TariffAltText = tariffAltText;
            this.MinPrice = minPrice;
            this.MaxPrice = maxPrice;
            this.Elements = elements;
            this.StartDateTime = startDateTime;
            this.EndDateTime = endDateTime;
            this.LastUpdated = lastUpdated;
            this.CreatedBy = createdBy;
        }

        /// <summary>
        /// Unique identifier for the tariff
        /// </summary>
        [JsonProperty("tariffId")]
        public string TariffId { get; set; }

        /// <summary>
        /// Tariff type classification
        /// </summary>
        [JsonProperty("tariffType")]
        public Models.TariffTypeEnum TariffType { get; set; }

        /// <summary>
        /// Gets or sets PowerRange.
        /// </summary>
        [JsonProperty("powerRange")]
        public Models.PowerRange PowerRange { get; set; }

        /// <summary>
        /// Internal identifier used by the platform
        /// </summary>
        [JsonProperty("internalId")]
        public string InternalId { get; set; }

        /// <summary>
        /// Unique identifier of the operator
        /// </summary>
        [JsonProperty("operatorId")]
        public string OperatorId { get; set; }

        /// <summary>
        /// Unique identifier of the provider
        /// </summary>
        [JsonProperty("providerId")]
        public string ProviderId { get; set; }

        /// <summary>
        /// ISO 4217 Currency Code
        /// </summary>
        [JsonProperty("currency")]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or sets TariffAltText.
        /// </summary>
        [JsonProperty("tariffAltText", NullValueHandling = NullValueHandling.Include)]
        public List<Models.TariffAltText> TariffAltText { get; set; }

        /// <summary>
        /// Gets or sets MinPrice.
        /// </summary>
        [JsonProperty("minPrice")]
        public double MinPrice { get; set; }

        /// <summary>
        /// Gets or sets MaxPrice.
        /// </summary>
        [JsonProperty("maxPrice")]
        public double MaxPrice { get; set; }

        /// <summary>
        /// Gets or sets Elements.
        /// </summary>
        [JsonProperty("elements")]
        public List<Models.TariffElement> Elements { get; set; }

        /// <summary>
        /// Gets or sets StartDateTime.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("startDateTime")]
        public DateTime StartDateTime { get; set; }

        /// <summary>
        /// Gets or sets EndDateTime.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("endDateTime")]
        public DateTime EndDateTime { get; set; }

        /// <summary>
        /// Gets or sets LastUpdated.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("lastUpdated")]
        public DateTime LastUpdated { get; set; }

        /// <summary>
        /// Identifier of the actor who created the tariff
        /// </summary>
        [JsonProperty("createdBy")]
        public string CreatedBy { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TariffV2 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is TariffV2 other &&
                (this.TariffId == null && other.TariffId == null ||
                 this.TariffId?.Equals(other.TariffId) == true) &&
                (this.TariffType.Equals(other.TariffType)) &&
                (this.PowerRange == null && other.PowerRange == null ||
                 this.PowerRange?.Equals(other.PowerRange) == true) &&
                (this.InternalId == null && other.InternalId == null ||
                 this.InternalId?.Equals(other.InternalId) == true) &&
                (this.OperatorId == null && other.OperatorId == null ||
                 this.OperatorId?.Equals(other.OperatorId) == true) &&
                (this.ProviderId == null && other.ProviderId == null ||
                 this.ProviderId?.Equals(other.ProviderId) == true) &&
                (this.Currency == null && other.Currency == null ||
                 this.Currency?.Equals(other.Currency) == true) &&
                (this.TariffAltText == null && other.TariffAltText == null ||
                 this.TariffAltText?.Equals(other.TariffAltText) == true) &&
                (this.MinPrice.Equals(other.MinPrice)) &&
                (this.MaxPrice.Equals(other.MaxPrice)) &&
                (this.Elements == null && other.Elements == null ||
                 this.Elements?.Equals(other.Elements) == true) &&
                (this.StartDateTime.Equals(other.StartDateTime)) &&
                (this.EndDateTime.Equals(other.EndDateTime)) &&
                (this.LastUpdated.Equals(other.LastUpdated)) &&
                (this.CreatedBy == null && other.CreatedBy == null ||
                 this.CreatedBy?.Equals(other.CreatedBy) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"TariffId = {this.TariffId ?? "null"}");
            toStringOutput.Add($"TariffType = {this.TariffType}");
            toStringOutput.Add($"PowerRange = {(this.PowerRange == null ? "null" : this.PowerRange.ToString())}");
            toStringOutput.Add($"InternalId = {this.InternalId ?? "null"}");
            toStringOutput.Add($"OperatorId = {this.OperatorId ?? "null"}");
            toStringOutput.Add($"ProviderId = {this.ProviderId ?? "null"}");
            toStringOutput.Add($"Currency = {this.Currency ?? "null"}");
            toStringOutput.Add($"TariffAltText = {(this.TariffAltText == null ? "null" : $"[{string.Join(", ", this.TariffAltText)} ]")}");
            toStringOutput.Add($"MinPrice = {this.MinPrice}");
            toStringOutput.Add($"MaxPrice = {this.MaxPrice}");
            toStringOutput.Add($"Elements = {(this.Elements == null ? "null" : $"[{string.Join(", ", this.Elements)} ]")}");
            toStringOutput.Add($"StartDateTime = {this.StartDateTime}");
            toStringOutput.Add($"EndDateTime = {this.EndDateTime}");
            toStringOutput.Add($"LastUpdated = {this.LastUpdated}");
            toStringOutput.Add($"CreatedBy = {this.CreatedBy ?? "null"}");
        }
    }
}