// <copyright file="TariffElement.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// TariffElement.
    /// </summary>
    public class TariffElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TariffElement"/> class.
        /// </summary>
        public TariffElement()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TariffElement"/> class.
        /// </summary>
        /// <param name="priceComponents">priceComponents.</param>
        /// <param name="restrictions">restrictions.</param>
        public TariffElement(
            List<Models.PriceComponent> priceComponents,
            Models.Restrictions restrictions = null)
        {
            this.PriceComponents = priceComponents;
            this.Restrictions = restrictions;
        }

        /// <summary>
        /// Gets or sets PriceComponents.
        /// </summary>
        [JsonProperty("priceComponents")]
        public List<Models.PriceComponent> PriceComponents { get; set; }

        /// <summary>
        /// Gets or sets Restrictions.
        /// </summary>
        [JsonProperty("restrictions", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Restrictions Restrictions { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TariffElement : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is TariffElement other &&
                (this.PriceComponents == null && other.PriceComponents == null ||
                 this.PriceComponents?.Equals(other.PriceComponents) == true) &&
                (this.Restrictions == null && other.Restrictions == null ||
                 this.Restrictions?.Equals(other.Restrictions) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"PriceComponents = {(this.PriceComponents == null ? "null" : $"[{string.Join(", ", this.PriceComponents)} ]")}");
            toStringOutput.Add($"Restrictions = {(this.Restrictions == null ? "null" : this.Restrictions.ToString())}");
        }
    }
}