// <copyright file="TariffAltText.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// TariffAltText.
    /// </summary>
    public class TariffAltText
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TariffAltText"/> class.
        /// </summary>
        public TariffAltText()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TariffAltText"/> class.
        /// </summary>
        /// <param name="language">language.</param>
        /// <param name="text">text.</param>
        public TariffAltText(
            string language,
            string text)
        {
            this.Language = language;
            this.Text = text;
        }

        /// <summary>
        /// ISO language code
        /// </summary>
        [JsonProperty("language")]
        public string Language { get; set; }

        /// <summary>
        /// Human readable tariff description
        /// </summary>
        [JsonProperty("text")]
        public string Text { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TariffAltText : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is TariffAltText other &&
                (this.Language == null && other.Language == null ||
                 this.Language?.Equals(other.Language) == true) &&
                (this.Text == null && other.Text == null ||
                 this.Text?.Equals(other.Text) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Language = {this.Language ?? "null"}");
            toStringOutput.Add($"Text = {this.Text ?? "null"}");
        }
    }
}