// <copyright file="TypeEnum.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace ShellEV.Standard.Models
{
    /// <summary>
    /// TypeEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum TypeEnum
    {
        /// <summary>
        /// TIME.
        /// </summary>
        [EnumMember(Value = "TIME")]
        TIME,

        /// <summary>
        /// ENERGY.
        /// </summary>
        [EnumMember(Value = "ENERGY")]
        ENERGY,

        /// <summary>
        /// FLAT.
        /// </summary>
        [EnumMember(Value = "FLAT")]
        FLAT,

        /// <summary>
        /// PARKINGTIME.
        /// </summary>
        [EnumMember(Value = "PARKING_TIME")]
        PARKINGTIME
    }
}