// <copyright file="LocationMarker.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace ShellEV.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<LocationMarker>),
        new[] {
            typeof(SingleLocationMarkerCase),
            typeof(MultiLocationMarkerCase)
        },
        new[] {
            "SingleLocation",
            "MultiLocation"
        },
        "markerType",
        true
    )]
    public abstract class LocationMarker
    {
        /// <summary>
        /// This is SingleLocationMarker case.
        /// </summary>
        /// <returns>
        /// The LocationMarker instance, wrapping the provided SingleLocationMarker value.
        /// </returns>
        public static LocationMarker FromSingleLocationMarker(SingleLocationMarker singleLocationMarker)
        {
            return new SingleLocationMarkerCase().Set(singleLocationMarker);
        }

        /// <summary>
        /// This is MultiLocationMarker case.
        /// </summary>
        /// <returns>
        /// The LocationMarker instance, wrapping the provided MultiLocationMarker value.
        /// </returns>
        public static LocationMarker FromMultiLocationMarker(MultiLocationMarker multiLocationMarker)
        {
            return new MultiLocationMarkerCase().Set(multiLocationMarker);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(Func<SingleLocationMarker, T> singleLocationMarker, Func<MultiLocationMarker, T> multiLocationMarker);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(Func<SingleLocationMarker, T> singleLocationMarker = null, Func<MultiLocationMarker, T> multiLocationMarker = null) =>
                Match(singleLocationMarker, multiLocationMarker);

        [JsonConverter(typeof(UnionTypeCaseConverter<SingleLocationMarkerCase, SingleLocationMarker>))]
        private sealed class SingleLocationMarkerCase : LocationMarker, ICaseValue<SingleLocationMarkerCase, SingleLocationMarker>
        {
            public SingleLocationMarker Value;

            public override T Match<T>(Func<SingleLocationMarker, T> singleLocationMarker, Func<MultiLocationMarker, T> multiLocationMarker) =>
                   singleLocationMarker != null ? singleLocationMarker(Value) : default;

            public SingleLocationMarkerCase Set(SingleLocationMarker value)
            {
                Value = value;
                return this;
            }

            public SingleLocationMarker Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is SingleLocationMarkerCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<MultiLocationMarkerCase, MultiLocationMarker>))]
        private sealed class MultiLocationMarkerCase : LocationMarker, ICaseValue<MultiLocationMarkerCase, MultiLocationMarker>
        {
            public MultiLocationMarker Value;

            public override T Match<T>(Func<SingleLocationMarker, T> singleLocationMarker, Func<MultiLocationMarker, T> multiLocationMarker) =>
                   multiLocationMarker != null ? multiLocationMarker(Value) : default;

            public MultiLocationMarkerCase Set(MultiLocationMarker value)
            {
                Value = value;
                return this;
            }

            public MultiLocationMarker Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is MultiLocationMarkerCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }
    }
}