// <copyright file="LocationMarkerV2.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace ShellEV.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<LocationMarkerV2>),
        new[] {
            typeof(SingleLocationMarkerV2Case),
            typeof(MultiLocationMarkerV2Case)
        },
        new[] {
            "SingleLocation",
            "MultiLocation"
        },
        "markerType",
        true
    )]
    public abstract class LocationMarkerV2
    {
        /// <summary>
        /// This is SingleLocationMarkerV2 case.
        /// </summary>
        /// <returns>
        /// The LocationMarkerV2 instance, wrapping the provided SingleLocationMarkerV2 value.
        /// </returns>
        public static LocationMarkerV2 FromSingleLocationMarkerV2(SingleLocationMarkerV2 singleLocationMarkerV2)
        {
            return new SingleLocationMarkerV2Case().Set(singleLocationMarkerV2);
        }

        /// <summary>
        /// This is MultiLocationMarkerV2 case.
        /// </summary>
        /// <returns>
        /// The LocationMarkerV2 instance, wrapping the provided MultiLocationMarkerV2 value.
        /// </returns>
        public static LocationMarkerV2 FromMultiLocationMarkerV2(MultiLocationMarkerV2 multiLocationMarkerV2)
        {
            return new MultiLocationMarkerV2Case().Set(multiLocationMarkerV2);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(Func<SingleLocationMarkerV2, T> singleLocationMarkerV2, Func<MultiLocationMarkerV2, T> multiLocationMarkerV2);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(Func<SingleLocationMarkerV2, T> singleLocationMarkerV2 = null, Func<MultiLocationMarkerV2, T> multiLocationMarkerV2 = null) =>
                Match(singleLocationMarkerV2, multiLocationMarkerV2);

        [JsonConverter(typeof(UnionTypeCaseConverter<SingleLocationMarkerV2Case, SingleLocationMarkerV2>))]
        private sealed class SingleLocationMarkerV2Case : LocationMarkerV2, ICaseValue<SingleLocationMarkerV2Case, SingleLocationMarkerV2>
        {
            public SingleLocationMarkerV2 Value;

            public override T Match<T>(Func<SingleLocationMarkerV2, T> singleLocationMarkerV2, Func<MultiLocationMarkerV2, T> multiLocationMarkerV2) =>
                   singleLocationMarkerV2 != null ? singleLocationMarkerV2(Value) : default;

            public SingleLocationMarkerV2Case Set(SingleLocationMarkerV2 value)
            {
                Value = value;
                return this;
            }

            public SingleLocationMarkerV2 Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is SingleLocationMarkerV2Case other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<MultiLocationMarkerV2Case, MultiLocationMarkerV2>))]
        private sealed class MultiLocationMarkerV2Case : LocationMarkerV2, ICaseValue<MultiLocationMarkerV2Case, MultiLocationMarkerV2>
        {
            public MultiLocationMarkerV2 Value;

            public override T Match<T>(Func<SingleLocationMarkerV2, T> singleLocationMarkerV2, Func<MultiLocationMarkerV2, T> multiLocationMarkerV2) =>
                   multiLocationMarkerV2 != null ? multiLocationMarkerV2(Value) : default;

            public MultiLocationMarkerV2Case Set(MultiLocationMarkerV2 value)
            {
                Value = value;
                return this;
            }

            public MultiLocationMarkerV2 Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is MultiLocationMarkerV2Case other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }
    }
}