// <copyright file="ShellEVClient.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Authentication;
using APIMatic.Core.Utilities;
using Microsoft.Extensions.Configuration;
using ShellEV.Standard.Authentication;
using ShellEV.Standard.Controllers;
using ShellEV.Standard.Http.Client;
using System;
using System.Collections.Generic;

namespace ShellEV.Standard
{
    /// <summary>
    /// The gateway for the SDK. This class acts as a factory for Controller and
    /// holds the configuration of the SDK.
    /// </summary>
    public sealed class ShellEVClient : IConfiguration
    {
        // A map of environments and their corresponding servers/baseurls
        private static readonly Dictionary<Environment, Dictionary<Enum, string>> EnvironmentsMap =
            new Dictionary<Environment, Dictionary<Enum, string>>
        {
            {
                Environment.SIT, new Dictionary<Enum, string>
                {
                    { Server.OAuthServer, "https://api-test.shell.com" },
                    { Server.Shell, "https://api-test.shell.com/ev" },
                }
            },
            {
                Environment.Production, new Dictionary<Enum, string>
                {
                    { Server.OAuthServer, "https://api.shell.com" },
                    { Server.Shell, "https://api.shell.com/ev" },
                }
            },
        };

        private readonly GlobalConfiguration globalConfiguration;
        private const string userAgent = "APIMATIC 3.0";
        private readonly HttpCallback httpCallback;
        private readonly Lazy<LocationsController> locations;
        private readonly Lazy<ChargingController> charging;
        private readonly Lazy<OAuthAuthorizationController> oAuthAuthorization;

        private ShellEVClient(
            Environment environment,
            ClientCredentialsAuthModel clientCredentialsAuthModel,
            HttpCallback httpCallback,
            IHttpClientConfiguration httpClientConfiguration)
        {
            this.Environment = environment;
            this.httpCallback = httpCallback;
            this.HttpClientConfiguration = httpClientConfiguration;
            ClientCredentialsAuthModel = clientCredentialsAuthModel;
            var clientCredentialsAuthManager = new ClientCredentialsAuthManager(clientCredentialsAuthModel,
                () => OAuthAuthorizationController);
            globalConfiguration = new GlobalConfiguration.Builder()
                .AuthManagers(new Dictionary<string, AuthManager> {
                    {"BearerAuth", clientCredentialsAuthManager},
                })
                .ApiCallback(httpCallback)
                .HttpConfiguration(httpClientConfiguration)
                .ServerUrls(EnvironmentsMap[environment], Server.Shell)
                .UserAgent(userAgent)
                .Build();
            ClientCredentialsAuth = clientCredentialsAuthManager;

            this.locations = new Lazy<LocationsController>(
                () => new LocationsController(globalConfiguration));
            this.charging = new Lazy<ChargingController>(
                () => new ChargingController(globalConfiguration));
            this.oAuthAuthorization = new Lazy<OAuthAuthorizationController>(
                () => new OAuthAuthorizationController(globalConfiguration));
        }

        /// <summary>
        /// Gets LocationsController controller.
        /// </summary>
        public LocationsController LocationsController => this.locations.Value;

        /// <summary>
        /// Gets ChargingController controller.
        /// </summary>
        public ChargingController ChargingController => this.charging.Value;

        /// <summary>
        /// Gets OAuthAuthorizationController controller.
        /// </summary>
        public OAuthAuthorizationController OAuthAuthorizationController => this.oAuthAuthorization.Value;

        /// <summary>
        /// Gets the configuration of the Http Client associated with this client.
        /// </summary>
        public IHttpClientConfiguration HttpClientConfiguration { get; }

        /// <summary>
        /// Gets Environment.
        /// Current API environment.
        /// </summary>
        public Environment Environment { get; }

        /// <summary>
        /// Gets http callback.
        /// </summary>
        public HttpCallback HttpCallback => this.httpCallback;

        /// <summary>
        /// Gets the credentials to use with ClientCredentialsAuth.
        /// </summary>
        public IClientCredentialsAuth ClientCredentialsAuth { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with ClientCredentialsAuth.
        /// </summary>
        public ClientCredentialsAuthModel ClientCredentialsAuthModel { get; private set; }

        /// <summary>
        /// Gets the URL for a particular alias in the current environment and appends
        /// it with template parameters.
        /// </summary>
        /// <param name="alias">Default value:SHELL.</param>
        /// <returns>Returns the baseurl.</returns>
        public string GetBaseUri(Server alias = Server.Shell)
        {
            return globalConfiguration.ServerUrl(alias);
        }

        /// <summary>
        /// Creates an object of the ShellEVClient using the values provided for the builder.
        /// </summary>
        /// <returns>Builder.</returns>
        public Builder ToBuilder()
        {
            Builder builder = new Builder()
                .Environment(this.Environment)
                .HttpCallback(httpCallback)
                .HttpClientConfig(config => config.Build());

            if (ClientCredentialsAuthModel != null)
            {
                builder.ClientCredentialsAuth(ClientCredentialsAuthModel.ToBuilder().Build());
            }

            return builder;
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            return
                $"Environment = {this.Environment}, " +
                $"HttpClientConfiguration = {this.HttpClientConfiguration}, ";
        }

        /// <summary>
        /// Creates the client using builder.
        /// </summary>
        /// <returns> ShellEVClient.</returns>
        internal static ShellEVClient CreateFromEnvironment()
        {
            var builder = new Builder();

            string environment = System.Environment.GetEnvironmentVariable("SHELL_EV_STANDARD_ENVIRONMENT");
            string oAuthClientId = System.Environment.GetEnvironmentVariable("SHELL_EV_STANDARD_O_AUTH_CLIENT_ID");
            string oAuthClientSecret = System.Environment.GetEnvironmentVariable("SHELL_EV_STANDARD_O_AUTH_CLIENT_SECRET");

            if (environment != null)
            {
                builder.Environment(CoreHelper.JsonDeserialize<Environment>($"\"{environment}\""));
            }

            if (oAuthClientId != null && oAuthClientSecret != null)
            {
                builder.ClientCredentialsAuth(new ClientCredentialsAuthModel
                .Builder(oAuthClientId, oAuthClientSecret)
                .Build());
            }

            return builder.Build();
        }

        /// <summary>
        /// Creates the client from configuration.
        /// </summary>
        /// <returns> ShellEVClient.</returns>
        public static ShellEVClient FromConfiguration(IConfigurationSection configuration) =>
            Builder.FromConfiguration(configuration).Build();

        /// <summary>
        /// Builder class.
        /// </summary>
        public class Builder
        {
            private Environment _environment = ShellEV.Standard.Environment.SIT;
            private ClientCredentialsAuthModel _clientCredentialsAuthModel = new ClientCredentialsAuthModel();
            private HttpClientConfiguration.Builder _httpClientConfig = new HttpClientConfiguration.Builder();
            private HttpCallback _httpCallback;

            /// <summary>
            /// Sets credentials for ClientCredentialsAuth.
            /// </summary>
            /// <param name="oAuthClientId">OAuthClientId.</param>
            /// <param name="oAuthClientSecret">OAuthClientSecret.</param>
            /// <returns>Builder.</returns>
            [Obsolete("This method is deprecated. Use ClientCredentialsAuth(clientCredentialsAuthModel) instead.")]
            public Builder ClientCredentialsAuth(string oAuthClientId, string oAuthClientSecret)
            {
                _clientCredentialsAuthModel = _clientCredentialsAuthModel.ToBuilder()
                    .OAuthClientId(oAuthClientId)
                    .OAuthClientSecret(oAuthClientSecret)
                    .Build();
                return this;
            }

            /// <summary>
            /// Sets OAuthToken.
            /// </summary>
            /// <param name="oAuthToken">OAuthToken.</param>
            /// <returns>Builder.</returns>
            [Obsolete("This method is deprecated. Use ClientCredentialsAuth(clientCredentialsAuthModel) instead.")]
            public Builder OAuthToken(Models.OAuthToken oAuthToken)
            {
                _clientCredentialsAuthModel = _clientCredentialsAuthModel.ToBuilder()
                    .OAuthToken(oAuthToken)
                    .Build();
                return this;
            }

            /// <summary>
            /// Sets credentials for ClientCredentialsAuth.
            /// </summary>
            /// <param name="clientCredentialsAuthModel">ClientCredentialsAuthModel.</param>
            /// <returns>Builder.</returns>
            public Builder ClientCredentialsAuth(ClientCredentialsAuthModel clientCredentialsAuthModel)
            {
                _clientCredentialsAuthModel = clientCredentialsAuthModel ??
                    throw new ArgumentNullException(nameof(clientCredentialsAuthModel));
                return this;
            }

            /// <summary>
            /// Sets Environment.
            /// </summary>
            /// <param name="environment"> Environment. </param>
            /// <returns> Builder. </returns>
            public Builder Environment(Environment environment)
            {
                _environment = environment;
                return this;
            }

            /// <summary>
            /// Sets HttpClientConfig.
            /// </summary>
            /// <param name="action"> Action. </param>
            /// <returns>Builder.</returns>
            public Builder HttpClientConfig(Action<HttpClientConfiguration.Builder> action)
            {
                if (action is null)
                {
                    throw new ArgumentNullException(nameof(action));
                }

                action(_httpClientConfig);
                return this;
            }

            private Builder HttpClientConfig(HttpClientConfiguration.Builder httpClientConfigurationBuilder)
            {
                if (httpClientConfigurationBuilder != null)
                {
                    _httpClientConfig = httpClientConfigurationBuilder;
                }

                return this;
            }

            /// <summary>
            /// Sets the HttpCallback for the Builder.
            /// </summary>
            /// <param name="httpCallback"> http callback. </param>
            /// <returns>Builder.</returns>
            public Builder HttpCallback(HttpCallback httpCallback)
            {
                _httpCallback = httpCallback;
                return this;
            }

            /// <summary>
            /// Creates an object of the ShellEVClient using the values provided for the builder.
            /// </summary>
            /// <returns>ShellEVClient.</returns>
            public ShellEVClient Build()
            {
                if (_clientCredentialsAuthModel.OAuthClientId == null || _clientCredentialsAuthModel.OAuthClientSecret == null)
                {
                    _clientCredentialsAuthModel = null;
                }
                return new ShellEVClient(
                    _environment,
                    _clientCredentialsAuthModel,
                    _httpCallback,
                    _httpClientConfig.Build());
            }

            /// <summary>
            /// Creates the client builder from configuration.
            /// </summary>
            /// <returns> Builder.</returns>
            public static Builder FromConfiguration(IConfigurationSection config)
            {
                var builder = new Builder();
                var options = config.Get<ShellEVClientOptions>();
                if (options == null) return builder;
                if (options.Environment != null)
                    builder.Environment(options.Environment.Value);
                if (options.ClientCredentialsAuth != null)
                    builder.ClientCredentialsAuth(ClientCredentialsAuthModel.FromOptions(options.ClientCredentialsAuth));
                if (options.HttpClientConfig != null)
                    builder.HttpClientConfig(Http.Client.HttpClientConfiguration.FromOptions(options.HttpClientConfig));
                return builder;
            }
        }

        public class ShellEVClientOptions
        {
            public Environment? Environment { get; set; }
            public ClientCredentialsAuthModelOptions ClientCredentialsAuth { get; set; }
            public HttpClientConfigurationOptions HttpClientConfig { get; set; }
        }
    }
}
