// <copyright file="LocationsController.cs" company="APIMatic">
// ShellEV.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using ShellEV.Standard.Exceptions;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace ShellEV.Standard.Controllers
{
    /// <summary>
    /// LocationsController.
    /// </summary>
    public class LocationsController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LocationsController"/> class.
        /// </summary>
        internal LocationsController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// This API Product provides the list of all public Shell Recharge locations. The list includes Shell Recharge network and locations available publicly through our roaming partners. The end point provides flexible search criteria in order to get the list of Shell Recharge Network. The end point provides the details such as the exact location/address of the site along with the up-to-date status information of all the charging units in the site. .
        /// Supported Search Options.
        /// * Based on status of the Charging units. Eg : Available or Occupied.
        /// * Based on available connector types.
        /// * Based on minimum Power output (in kW) available.
        /// * Based on a specific charging unit ID (EVSE ID) .
        /// </summary>
        /// <param name="requestId"><![CDATA[Required parameter: RequestId must be unique identifier value that can be used by the consumer to correlate each request /response .<br>Format.<br> Its canonical textual representation, the 16 octets of a UUID are represented as 32 hexadecimal (base-16) digits, displayed in five groups separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 hexadecimal characters and 4 hyphens) <br>.]]></param>
        /// <param name="evseStatus">Optional parameter: Filter by Locations that have the given status.</param>
        /// <param name="connectorTypes">Optional parameter: Filter by Locations that have Connectors with the set of Connector Types.</param>
        /// <param name="connectorMinPower">Optional parameter: Filter by Locations that have a Connector with at least this power output (in kW).</param>
        /// <param name="authorizationMethods">Optional parameter: Filter by Locations that support the given Authorization Methods.</param>
        /// <param name="withOperatorName">Optional parameter: Return operator name in marker response object.</param>
        /// <param name="evseId">Optional parameter: optional Standard EVSE (Electric Vehicle Supply Equipment) Id identifier (ISO-IEC-15118).</param>
        /// <param name="locationExternalId">Optional parameter: Filter by Locations with the given externalId. (Unique Location externalID provided by Shell Recharge).</param>
        /// <param name="evseExternalId">Optional parameter: Filter by Locations that have an Evse with the given External Id. (Unique individual EVSE externalID provided by Shell Recharge).</param>
        /// <param name="pageNumber">Optional parameter: Restrict the response list by providing a specific set of page Number. Set perPage parameter also when page Number is used..</param>
        /// <param name="perPage">Optional parameter: Restrict the number of sites in response per page..</param>
        /// <param name="updatedSince">Optional parameter: ZonedDateTime as string.</param>
        /// <param name="country">Optional parameter: Filter by Locations that are at least in one of the given countries (specified using ISO 3166-1 alpha-3 codes).</param>
        /// <param name="excludeCountry">Optional parameter: Filter by Locations that are not in one of the given countries (specified using ISO 3166-1 alpha-3 codes).</param>
        /// <returns>Returns the Models.ResponseV2 response from the API call.</returns>
        public Models.ResponseV2 GetEVLocations(
                Guid requestId,
                Models.EvseStatusEnum? evseStatus = null,
                Models.ConnectorTypesEnum? connectorTypes = null,
                double? connectorMinPower = null,
                Models.SingleLocationMarkerAuthorizationMethodsItemsEnum? authorizationMethods = null,
                bool? withOperatorName = null,
                string evseId = null,
                string locationExternalId = null,
                string evseExternalId = null,
                int? pageNumber = null,
                int? perPage = null,
                string updatedSince = null,
                List<string> country = null,
                List<string> excludeCountry = null)
            => CoreHelper.RunTask(GetEVLocationsAsync(requestId, evseStatus, connectorTypes, connectorMinPower, authorizationMethods, withOperatorName, evseId, locationExternalId, evseExternalId, pageNumber, perPage, updatedSince, country, excludeCountry));

        /// <summary>
        /// This API Product provides the list of all public Shell Recharge locations. The list includes Shell Recharge network and locations available publicly through our roaming partners. The end point provides flexible search criteria in order to get the list of Shell Recharge Network. The end point provides the details such as the exact location/address of the site along with the up-to-date status information of all the charging units in the site. .
        /// Supported Search Options.
        /// * Based on status of the Charging units. Eg : Available or Occupied.
        /// * Based on available connector types.
        /// * Based on minimum Power output (in kW) available.
        /// * Based on a specific charging unit ID (EVSE ID) .
        /// </summary>
        /// <param name="requestId"><![CDATA[Required parameter: RequestId must be unique identifier value that can be used by the consumer to correlate each request /response .<br>Format.<br> Its canonical textual representation, the 16 octets of a UUID are represented as 32 hexadecimal (base-16) digits, displayed in five groups separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 hexadecimal characters and 4 hyphens) <br>.]]></param>
        /// <param name="evseStatus">Optional parameter: Filter by Locations that have the given status.</param>
        /// <param name="connectorTypes">Optional parameter: Filter by Locations that have Connectors with the set of Connector Types.</param>
        /// <param name="connectorMinPower">Optional parameter: Filter by Locations that have a Connector with at least this power output (in kW).</param>
        /// <param name="authorizationMethods">Optional parameter: Filter by Locations that support the given Authorization Methods.</param>
        /// <param name="withOperatorName">Optional parameter: Return operator name in marker response object.</param>
        /// <param name="evseId">Optional parameter: optional Standard EVSE (Electric Vehicle Supply Equipment) Id identifier (ISO-IEC-15118).</param>
        /// <param name="locationExternalId">Optional parameter: Filter by Locations with the given externalId. (Unique Location externalID provided by Shell Recharge).</param>
        /// <param name="evseExternalId">Optional parameter: Filter by Locations that have an Evse with the given External Id. (Unique individual EVSE externalID provided by Shell Recharge).</param>
        /// <param name="pageNumber">Optional parameter: Restrict the response list by providing a specific set of page Number. Set perPage parameter also when page Number is used..</param>
        /// <param name="perPage">Optional parameter: Restrict the number of sites in response per page..</param>
        /// <param name="updatedSince">Optional parameter: ZonedDateTime as string.</param>
        /// <param name="country">Optional parameter: Filter by Locations that are at least in one of the given countries (specified using ISO 3166-1 alpha-3 codes).</param>
        /// <param name="excludeCountry">Optional parameter: Filter by Locations that are not in one of the given countries (specified using ISO 3166-1 alpha-3 codes).</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.ResponseV2 response from the API call.</returns>
        public async Task<Models.ResponseV2> GetEVLocationsAsync(
                Guid requestId,
                Models.EvseStatusEnum? evseStatus = null,
                Models.ConnectorTypesEnum? connectorTypes = null,
                double? connectorMinPower = null,
                Models.SingleLocationMarkerAuthorizationMethodsItemsEnum? authorizationMethods = null,
                bool? withOperatorName = null,
                string evseId = null,
                string locationExternalId = null,
                string evseExternalId = null,
                int? pageNumber = null,
                int? perPage = null,
                string updatedSince = null,
                List<string> country = null,
                List<string> excludeCountry = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ResponseV2>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/v2/locations")
                  .WithAuth("BearerAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("RequestId", requestId))
                      .Query(query => query.Setup("evseStatus", (evseStatus.HasValue) ? CoreHelper.JsonSerialize(evseStatus.Value).Trim('\"') : null))
                      .Query(query => query.Setup("connectorTypes", (connectorTypes.HasValue) ? CoreHelper.JsonSerialize(connectorTypes.Value).Trim('\"') : null))
                      .Query(query => query.Setup("connectorMinPower", connectorMinPower))
                      .Query(query => query.Setup("authorizationMethods", (authorizationMethods.HasValue) ? CoreHelper.JsonSerialize(authorizationMethods.Value).Trim('\"') : null))
                      .Query(query => query.Setup("withOperatorName", withOperatorName))
                      .Query(query => query.Setup("evseId", evseId))
                      .Query(query => query.Setup("locationExternalId", locationExternalId))
                      .Query(query => query.Setup("evseExternalId", evseExternalId))
                      .Query(query => query.Setup("pageNumber", pageNumber))
                      .Query(query => query.Setup("perPage", perPage))
                      .Query(query => query.Setup("updatedSince", updatedSince))
                      .Query(query => query.Setup("country", country))
                      .Query(query => query.Setup("excludeCountry", excludeCountry))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).", (errorReason, context) => new BadRequestException(errorReason, context)))
                  .ErrorCase("401", CreateErrorCase("The request has not been applied because it lacks valid authentication credentials for the target resource.", (errorReason, context) => new UnauthorizedException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Location Not Found", (errorReason, context) => new NotFoundException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("The Request reached maximum allocated rate limit", (errorReason, context) => new TooManyRequestsException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server error", (errorReason, context) => new InternalServerErrorException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service unavailable", (errorReason, context) => new ServiceunavailableException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// This API provides the details on a single Shell Recharge location. .
        /// The query for a single location is to be made using the Unique Internal identifier used to refer to this Location by Shell Recharge. (Uid from List of locations API).
        /// </summary>
        /// <param name="requestId"><![CDATA[Required parameter: RequestId must be unique identifier value that can be used by the consumer to correlate each request /response .<br>Format.<br> Its canonical textual representation, the 16 octets of a UUID are represented as 32 hexadecimal (base-16) digits, displayed in five groups separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 hexadecimal characters and 4 hyphens) <br>.]]></param>
        /// <param name="id">Required parameter: Unique Uid of the location from List of locations API.</param>
        /// <param name="providerId">Optional parameter: ProviderId is mandatory in order to get the tariff information as part of API response..</param>
        /// <param name="since">Optional parameter: to get the locations modified after a date.</param>
        /// <returns>Returns the Models.SearchByIdResponse response from the API call.</returns>
        public Models.SearchByIdResponse EvLocationsByID(
                Guid requestId,
                string id,
                string providerId = null,
                string since = null)
            => CoreHelper.RunTask(EvLocationsByIDAsync(requestId, id, providerId, since));

        /// <summary>
        /// This API provides the details on a single Shell Recharge location. .
        /// The query for a single location is to be made using the Unique Internal identifier used to refer to this Location by Shell Recharge. (Uid from List of locations API).
        /// </summary>
        /// <param name="requestId"><![CDATA[Required parameter: RequestId must be unique identifier value that can be used by the consumer to correlate each request /response .<br>Format.<br> Its canonical textual representation, the 16 octets of a UUID are represented as 32 hexadecimal (base-16) digits, displayed in five groups separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 hexadecimal characters and 4 hyphens) <br>.]]></param>
        /// <param name="id">Required parameter: Unique Uid of the location from List of locations API.</param>
        /// <param name="providerId">Optional parameter: ProviderId is mandatory in order to get the tariff information as part of API response..</param>
        /// <param name="since">Optional parameter: to get the locations modified after a date.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.SearchByIdResponse response from the API call.</returns>
        public async Task<Models.SearchByIdResponse> EvLocationsByIDAsync(
                Guid requestId,
                string id,
                string providerId = null,
                string since = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.SearchByIdResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/v2/locations/{id}")
                  .WithAuth("BearerAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("RequestId", requestId))
                      .Template(template => template.Setup("id", id))
                      .Query(query => query.Setup("providerId", providerId))
                      .Query(query => query.Setup("since", since))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).", (errorReason, context) => new BadRequestException(errorReason, context)))
                  .ErrorCase("401", CreateErrorCase("The request has not been applied because it lacks valid authentication credentials for the target resource.", (errorReason, context) => new UnauthorizedException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Location Not Found", (errorReason, context) => new NotFoundException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("The Request reached maximum allocated rate limit", (errorReason, context) => new TooManyRequestsException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server error", (errorReason, context) => new InternalServerErrorException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service unavailable", (errorReason, context) => new ServiceunavailableException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// This API provides the list of all nearby Shell Recharge locations based on the latitude and longitude provided in the request. .
        /// The list includes all Shell Recharge network and all sites available through our roaming partners.
        /// The end point provides the details such as the exact location/address of the site along with the up-to-date status information of all the charging units in the site. .
        /// Supported Search Options.
        /// * Based on latitude and longitude of the location. (Mandatory).
        /// * Based on status of the Charging units. Eg : Available or Occupied.
        /// * Based on available connector types.
        /// * Based on minimum Power output (in kW) available.
        /// </summary>
        /// <param name="requestId"><![CDATA[Required parameter: RequestId must be unique identifier value that can be used by the consumer to correlate each request /response .<br>Format.<br> Its canonical textual representation, the 16 octets of a UUID are represented as 32 hexadecimal (base-16) digits, displayed in five groups separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 hexadecimal characters and 4 hyphens) <br>.]]></param>
        /// <param name="latitude">Required parameter: Latitude to get Shell Recharge Locations nearby.</param>
        /// <param name="longitude">Required parameter: Longitude to get Shell Recharge Locations nearby.</param>
        /// <param name="limit">Optional parameter: Maximum number of Locations to retrieve.</param>
        /// <param name="locationExternalId">Optional parameter: Filter by Locations with the given externalId Identifier as given by the Shell Recharge Operator, unique for that Operator.</param>
        /// <param name="evseId">Optional parameter: Filter by Locations that have an Evse with the given Evse Id.</param>
        /// <param name="evseExternalId">Optional parameter: Filter by Locations that have an Evse with the given External Id Identifier of the Evse as given by the Operator, unique for that Operator.</param>
        /// <param name="operatorName">Optional parameter: Filter by Locations that have the given operator.</param>
        /// <param name="evseStatus">Optional parameter: Filter by Locations that have the given status.</param>
        /// <param name="connectorTypes">Optional parameter: Filter by Locations that have Connectors with these Connector Types.</param>
        /// <param name="connectorMinPower">Optional parameter: Filter by Locations that have a Connector with at least this power output (in kW).</param>
        /// <param name="authorizationMethods">Optional parameter: Filter by Locations that support the given Authorization Methods.</param>
        /// <param name="withOperatorName">Optional parameter: Return operator name in marker object (only for marker type Single ChargePoint).</param>
        /// <param name="withMaxPower">Optional parameter: Return maximum power in kW across all locations grouped in this marker (disregarding availability).</param>
        /// <param name="country">Optional parameter: Filter by Locations that are at least in one of the given countries (specified using ISO 3166-1 alpha-3 codes).</param>
        /// <param name="excludeCountry">Optional parameter: Filter by Locations that are not in one of the given countries (specified using ISO 3166-1 alpha-3 codes).</param>
        /// <returns>Returns the Models.ResponseV2 response from the API call.</returns>
        public Models.ResponseV2 NearbyLocations(
                Guid requestId,
                double latitude,
                double longitude,
                double? limit = 25,
                string locationExternalId = null,
                string evseId = null,
                string evseExternalId = null,
                string operatorName = null,
                Models.EvseStatusEnum? evseStatus = null,
                Models.ConnectorTypesEnum? connectorTypes = null,
                double? connectorMinPower = null,
                Models.SingleLocationMarkerAuthorizationMethodsItemsEnum? authorizationMethods = null,
                bool? withOperatorName = null,
                bool? withMaxPower = null,
                List<string> country = null,
                List<string> excludeCountry = null)
            => CoreHelper.RunTask(NearbyLocationsAsync(requestId, latitude, longitude, limit, locationExternalId, evseId, evseExternalId, operatorName, evseStatus, connectorTypes, connectorMinPower, authorizationMethods, withOperatorName, withMaxPower, country, excludeCountry));

        /// <summary>
        /// This API provides the list of all nearby Shell Recharge locations based on the latitude and longitude provided in the request. .
        /// The list includes all Shell Recharge network and all sites available through our roaming partners.
        /// The end point provides the details such as the exact location/address of the site along with the up-to-date status information of all the charging units in the site. .
        /// Supported Search Options.
        /// * Based on latitude and longitude of the location. (Mandatory).
        /// * Based on status of the Charging units. Eg : Available or Occupied.
        /// * Based on available connector types.
        /// * Based on minimum Power output (in kW) available.
        /// </summary>
        /// <param name="requestId"><![CDATA[Required parameter: RequestId must be unique identifier value that can be used by the consumer to correlate each request /response .<br>Format.<br> Its canonical textual representation, the 16 octets of a UUID are represented as 32 hexadecimal (base-16) digits, displayed in five groups separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 hexadecimal characters and 4 hyphens) <br>.]]></param>
        /// <param name="latitude">Required parameter: Latitude to get Shell Recharge Locations nearby.</param>
        /// <param name="longitude">Required parameter: Longitude to get Shell Recharge Locations nearby.</param>
        /// <param name="limit">Optional parameter: Maximum number of Locations to retrieve.</param>
        /// <param name="locationExternalId">Optional parameter: Filter by Locations with the given externalId Identifier as given by the Shell Recharge Operator, unique for that Operator.</param>
        /// <param name="evseId">Optional parameter: Filter by Locations that have an Evse with the given Evse Id.</param>
        /// <param name="evseExternalId">Optional parameter: Filter by Locations that have an Evse with the given External Id Identifier of the Evse as given by the Operator, unique for that Operator.</param>
        /// <param name="operatorName">Optional parameter: Filter by Locations that have the given operator.</param>
        /// <param name="evseStatus">Optional parameter: Filter by Locations that have the given status.</param>
        /// <param name="connectorTypes">Optional parameter: Filter by Locations that have Connectors with these Connector Types.</param>
        /// <param name="connectorMinPower">Optional parameter: Filter by Locations that have a Connector with at least this power output (in kW).</param>
        /// <param name="authorizationMethods">Optional parameter: Filter by Locations that support the given Authorization Methods.</param>
        /// <param name="withOperatorName">Optional parameter: Return operator name in marker object (only for marker type Single ChargePoint).</param>
        /// <param name="withMaxPower">Optional parameter: Return maximum power in kW across all locations grouped in this marker (disregarding availability).</param>
        /// <param name="country">Optional parameter: Filter by Locations that are at least in one of the given countries (specified using ISO 3166-1 alpha-3 codes).</param>
        /// <param name="excludeCountry">Optional parameter: Filter by Locations that are not in one of the given countries (specified using ISO 3166-1 alpha-3 codes).</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.ResponseV2 response from the API call.</returns>
        public async Task<Models.ResponseV2> NearbyLocationsAsync(
                Guid requestId,
                double latitude,
                double longitude,
                double? limit = 25,
                string locationExternalId = null,
                string evseId = null,
                string evseExternalId = null,
                string operatorName = null,
                Models.EvseStatusEnum? evseStatus = null,
                Models.ConnectorTypesEnum? connectorTypes = null,
                double? connectorMinPower = null,
                Models.SingleLocationMarkerAuthorizationMethodsItemsEnum? authorizationMethods = null,
                bool? withOperatorName = null,
                bool? withMaxPower = null,
                List<string> country = null,
                List<string> excludeCountry = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ResponseV2>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/v2/locations/nearby")
                  .WithAuth("BearerAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("RequestId", requestId))
                      .Query(query => query.Setup("latitude", latitude))
                      .Query(query => query.Setup("longitude", longitude))
                      .Query(query => query.Setup("limit", limit ?? 25))
                      .Query(query => query.Setup("locationExternalId", locationExternalId))
                      .Query(query => query.Setup("evseId", evseId))
                      .Query(query => query.Setup("evseExternalId", evseExternalId))
                      .Query(query => query.Setup("operatorName", operatorName))
                      .Query(query => query.Setup("evseStatus", (evseStatus.HasValue) ? CoreHelper.JsonSerialize(evseStatus.Value).Trim('\"') : null))
                      .Query(query => query.Setup("connectorTypes", (connectorTypes.HasValue) ? CoreHelper.JsonSerialize(connectorTypes.Value).Trim('\"') : null))
                      .Query(query => query.Setup("connectorMinPower", connectorMinPower))
                      .Query(query => query.Setup("authorizationMethods", (authorizationMethods.HasValue) ? CoreHelper.JsonSerialize(authorizationMethods.Value).Trim('\"') : null))
                      .Query(query => query.Setup("withOperatorName", withOperatorName))
                      .Query(query => query.Setup("withMaxPower", withMaxPower))
                      .Query(query => query.Setup("country", country))
                      .Query(query => query.Setup("excludeCountry", excludeCountry))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).", (errorReason, context) => new BadRequestException(errorReason, context)))
                  .ErrorCase("401", CreateErrorCase("The request has not been applied because it lacks valid authentication credentials for the target resource.", (errorReason, context) => new UnauthorizedException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Location Not Found", (errorReason, context) => new NotFoundException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("The Request reached maximum allocated rate limit", (errorReason, context) => new TooManyRequestsException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server error", (errorReason, context) => new InternalServerErrorException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service unavailable", (errorReason, context) => new ServiceunavailableException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// This API, when given a set of bounds on the geographical front (East,West, North, South) will return a set of Markers that fall within the requested bounds. The API will automatically group locations at the same position on the map into one Marker. .
        /// The API also provide further search options to filter the result set. .
        ///   * Based on status of the Charging units. Eg : Available or Occupied.
        ///   * Based on available connector types.
        ///   * Based on minimum Power output (in kW) available.
        /// </summary>
        /// <param name="requestId"><![CDATA[Required parameter: RequestId must be unique identifier value that can be used by the consumer to correlate each request /response .<br>Format.<br> Its canonical textual representation, the 16 octets of a UUID are represented as 32 hexadecimal (base-16) digits, displayed in five groups separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 hexadecimal characters and 4 hyphens) <br>.]]></param>
        /// <param name="west">Required parameter: Longitude of the western bound to get the Shell Recharge Locations.</param>
        /// <param name="south">Required parameter: Latitude of the southern bound to get the Shell Recharge Locations.</param>
        /// <param name="east">Required parameter: Longitude of the eastern bound to get the Shell Recharge Locations.</param>
        /// <param name="north">Required parameter: Latitude of the northern bound to get the Shell Recharge Locations.</param>
        /// <param name="zoom">Required parameter: Zoom level to show ex: (1: World, 5: Landmass/continent, 10: City, 15: Streets, 20: Buildings).</param>
        /// <param name="evseStatus">Optional parameter: Filter by Locations that have the given status.</param>
        /// <param name="connectorTypes">Optional parameter: Filter by Locations that have Connectors with the set of Connector Types.</param>
        /// <param name="connectorMinPower">Optional parameter: Filter by Locations that have a Connector with at least this power output (in kW).</param>
        /// <param name="authorizationMethods">Optional parameter: Filter by Locations that support the given Authorization Methods.</param>
        /// <param name="withOperatorName">Optional parameter: Return operator name in marker object (only for marker type SingleChargePoint).</param>
        /// <param name="withMaxPower">Optional parameter: Return maximum power in kW across all locations grouped in this marker (disregarding availability).</param>
        /// <param name="locationExternalId">Optional parameter: Filter by Locations with the given externalId. (Unique Location externalID provided by Shell Recharge).</param>
        /// <param name="evseId">Optional parameter: Filter by Locations that have an Evse with the given Evse Id.</param>
        /// <param name="evseExternalId">Optional parameter: Filter by Locations that have an Evse with the given External Id Identifier of the Evse as given by the Operator, unique for that Operator.</param>
        /// <param name="operatorName">Optional parameter: Filter by Locations that have the given operator.</param>
        /// <param name="country">Optional parameter: Filter by Locations that are at least in one of the given countries (specified using ISO 3166-1 alpha-3 codes).</param>
        /// <param name="excludeCountry">Optional parameter: Filter by Locations that are not in one of the given countries (specified using ISO 3166-1 alpha-3 codes).</param>
        /// <returns>Returns the Models.SingleLocationMarkerResponseV2 response from the API call.</returns>
        public Models.SingleLocationMarkerResponseV2 LocationsMarkers(
                Guid requestId,
                double west,
                double south,
                double east,
                double north,
                string zoom,
                Models.EvseStatusEnum? evseStatus = null,
                Models.ConnectorTypesEnum? connectorTypes = null,
                double? connectorMinPower = null,
                Models.SingleLocationMarkerAuthorizationMethodsItemsEnum? authorizationMethods = null,
                bool? withOperatorName = null,
                bool? withMaxPower = null,
                string locationExternalId = null,
                string evseId = null,
                string evseExternalId = null,
                string operatorName = null,
                List<string> country = null,
                List<string> excludeCountry = null)
            => CoreHelper.RunTask(LocationsMarkersAsync(requestId, west, south, east, north, zoom, evseStatus, connectorTypes, connectorMinPower, authorizationMethods, withOperatorName, withMaxPower, locationExternalId, evseId, evseExternalId, operatorName, country, excludeCountry));

        /// <summary>
        /// This API, when given a set of bounds on the geographical front (East,West, North, South) will return a set of Markers that fall within the requested bounds. The API will automatically group locations at the same position on the map into one Marker. .
        /// The API also provide further search options to filter the result set. .
        ///   * Based on status of the Charging units. Eg : Available or Occupied.
        ///   * Based on available connector types.
        ///   * Based on minimum Power output (in kW) available.
        /// </summary>
        /// <param name="requestId"><![CDATA[Required parameter: RequestId must be unique identifier value that can be used by the consumer to correlate each request /response .<br>Format.<br> Its canonical textual representation, the 16 octets of a UUID are represented as 32 hexadecimal (base-16) digits, displayed in five groups separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 hexadecimal characters and 4 hyphens) <br>.]]></param>
        /// <param name="west">Required parameter: Longitude of the western bound to get the Shell Recharge Locations.</param>
        /// <param name="south">Required parameter: Latitude of the southern bound to get the Shell Recharge Locations.</param>
        /// <param name="east">Required parameter: Longitude of the eastern bound to get the Shell Recharge Locations.</param>
        /// <param name="north">Required parameter: Latitude of the northern bound to get the Shell Recharge Locations.</param>
        /// <param name="zoom">Required parameter: Zoom level to show ex: (1: World, 5: Landmass/continent, 10: City, 15: Streets, 20: Buildings).</param>
        /// <param name="evseStatus">Optional parameter: Filter by Locations that have the given status.</param>
        /// <param name="connectorTypes">Optional parameter: Filter by Locations that have Connectors with the set of Connector Types.</param>
        /// <param name="connectorMinPower">Optional parameter: Filter by Locations that have a Connector with at least this power output (in kW).</param>
        /// <param name="authorizationMethods">Optional parameter: Filter by Locations that support the given Authorization Methods.</param>
        /// <param name="withOperatorName">Optional parameter: Return operator name in marker object (only for marker type SingleChargePoint).</param>
        /// <param name="withMaxPower">Optional parameter: Return maximum power in kW across all locations grouped in this marker (disregarding availability).</param>
        /// <param name="locationExternalId">Optional parameter: Filter by Locations with the given externalId. (Unique Location externalID provided by Shell Recharge).</param>
        /// <param name="evseId">Optional parameter: Filter by Locations that have an Evse with the given Evse Id.</param>
        /// <param name="evseExternalId">Optional parameter: Filter by Locations that have an Evse with the given External Id Identifier of the Evse as given by the Operator, unique for that Operator.</param>
        /// <param name="operatorName">Optional parameter: Filter by Locations that have the given operator.</param>
        /// <param name="country">Optional parameter: Filter by Locations that are at least in one of the given countries (specified using ISO 3166-1 alpha-3 codes).</param>
        /// <param name="excludeCountry">Optional parameter: Filter by Locations that are not in one of the given countries (specified using ISO 3166-1 alpha-3 codes).</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.SingleLocationMarkerResponseV2 response from the API call.</returns>
        public async Task<Models.SingleLocationMarkerResponseV2> LocationsMarkersAsync(
                Guid requestId,
                double west,
                double south,
                double east,
                double north,
                string zoom,
                Models.EvseStatusEnum? evseStatus = null,
                Models.ConnectorTypesEnum? connectorTypes = null,
                double? connectorMinPower = null,
                Models.SingleLocationMarkerAuthorizationMethodsItemsEnum? authorizationMethods = null,
                bool? withOperatorName = null,
                bool? withMaxPower = null,
                string locationExternalId = null,
                string evseId = null,
                string evseExternalId = null,
                string operatorName = null,
                List<string> country = null,
                List<string> excludeCountry = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.SingleLocationMarkerResponseV2>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/v2/locations/markers")
                  .WithAuth("BearerAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("RequestId", requestId))
                      .Query(query => query.Setup("west", west))
                      .Query(query => query.Setup("south", south))
                      .Query(query => query.Setup("east", east))
                      .Query(query => query.Setup("north", north))
                      .Query(query => query.Setup("zoom", zoom))
                      .Query(query => query.Setup("evseStatus", (evseStatus.HasValue) ? CoreHelper.JsonSerialize(evseStatus.Value).Trim('\"') : null))
                      .Query(query => query.Setup("connectorTypes", (connectorTypes.HasValue) ? CoreHelper.JsonSerialize(connectorTypes.Value).Trim('\"') : null))
                      .Query(query => query.Setup("connectorMinPower", connectorMinPower))
                      .Query(query => query.Setup("authorizationMethods", (authorizationMethods.HasValue) ? CoreHelper.JsonSerialize(authorizationMethods.Value).Trim('\"') : null))
                      .Query(query => query.Setup("withOperatorName", withOperatorName))
                      .Query(query => query.Setup("withMaxPower", withMaxPower))
                      .Query(query => query.Setup("locationExternalId", locationExternalId))
                      .Query(query => query.Setup("evseId", evseId))
                      .Query(query => query.Setup("evseExternalId", evseExternalId))
                      .Query(query => query.Setup("operatorName", operatorName))
                      .Query(query => query.Setup("country", country))
                      .Query(query => query.Setup("excludeCountry", excludeCountry))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).", (errorReason, context) => new BadRequestException(errorReason, context)))
                  .ErrorCase("401", CreateErrorCase("The request has not been applied because it lacks valid authentication credentials for the target resource.", (errorReason, context) => new UnauthorizedException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Location Not Found", (errorReason, context) => new NotFoundException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("The Request reached maximum allocated rate limit", (errorReason, context) => new TooManyRequestsException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal server error", (errorReason, context) => new InternalServerErrorException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service unavailable", (errorReason, context) => new ServiceunavailableException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}